//
// Created by chenyilyang on 12/16/20.
//

#ifndef MYNATIAVEAPPLICATION_SAMPLETYPE_H
#define MYNATIAVEAPPLICATION_SAMPLETYPE_H
#define SHADER_TYPE_NORMAL 0
#define SHADER_TYPE_FBO 3
#endif //MYNATIAVEAPPLICATION_SAMPLETYPE_H
